apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-config
data:
  CLUSTER_NAME: "K8s Test Lab"

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-lab-service
spec:
  selector:
    app: k8s-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-lab
  template:
    metadata:
      labels:
        app: k8s-lab
    spec:
      containers:
      - name: web
        image: your-dockerhub/k8s-lab:latest
        ports:
        - containerPort: 5000
        env:
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: lab-config
              key: CLUSTER_NAME
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
